const products = [
    {
      id: 0,
      title: 'Entrée 1',
      category: 'Entrée',
      price: 7.99,
      description: 'Une délicieuse entrée.',
      allergens: ['gluten', 'lactose'],
    },
    {
      id: 1,
      title: 'Entrée 2',
      category: 'Entrée',
      price: 8.49,
      description: 'Une autre entrée délicieuse.',
      allergens: ['noix', 'soja'],
    },
    {
      id: 2,
      title: 'Plat 1',
      category: 'Plat',
      price: 15.99,
      description: 'Un savoureux plat principal.',
      allergens: ['gluten'],
    },
    {
      id: 3,
      title: 'Dessert 1',
      category: 'Dessert',
      price: 5.49,
      description: 'Un délicieux dessert.',
      allergens: [],
    },
    {
      id: 4,
      title: 'Soupe 1',
      category: 'Soupe',
      price: 6.99,
      description: 'Une soupe réconfortante.',
      allergens: ['lactose'],
    },
    {
      id: 5,
      title: 'Plat 2',
      category: 'Plat',
      price: 12.99,
      description: 'Un autre plat principal délicieux.',
      allergens: [],
    },
    {
      id: 6,
      title: 'Fromage 1',
      category: 'Fromage',
      price: 9.99,
      description: 'Un assortiment de fromages.',
      allergens: ['lactose'],
    },
    {
      id: 7,
      title: 'Entrée 3',
      category: 'Entrée',
      price: 6.49,
      description: 'Encore une entrée succulente.',
      allergens: ['soja'],
    },
    {
      id: 8,
      title: 'Dessert 2',
      category: 'Dessert',
      price: 7.99,
      description: 'Un deuxième dessert délicieux.',
      allergens: ['gluten', 'lactose'],
    },
    {
      id: 9,
      title: 'Plat 3',
      category: 'Plat',
      price: 14.49,
      description: 'Un plat principal exquis.',
      allergens: ['noix'],
    },
  ];

  export default products;
